### ISSUE TITLE
Is that the same as Outline?

### ISSUE THREAD

**Issue by M-Amrollahi** [jacob-schmitt/liberty#2]
Is that the same as Outline?
In spite of the fact that we can connect to our Outline server, Outline does not transfer any data.

**Comment by jacob-schmitt** [comment]
@M-Amrollahi:

Not really. The Outline is a project built on top of the good old _Shadowsocks_. I can say it's relatively easy for the DPI to detect and block Outline connections.

**ShadowsocksR**, on the other hand, is also a customized version of Shadowsocks, but with great obfuscation and authentication features. The further development, however, has been stopped for a few years now.

Then, we've got **V2Ray** which is, in my opinion, superior to all of the techniques mentioned before.
